# Project: Project1
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 113.10.1.o
LINKOBJ  = 113.10.1.o
LIBS     = -L"C:/Users/÷Ïº“’Í/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/÷Ïº“’Í/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/÷Ïº“’Í/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/÷Ïº“’Í/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/÷Ïº“’Í/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/÷Ïº“’Í/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/÷Ïº“’Í/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/÷Ïº“’Í/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/÷Ïº“’Í/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = 113-10.1.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

113.10.1.o: 113.10.1.c
	$(CC) -c 113.10.1.c -o 113.10.1.o $(CFLAGS)
