# Project: 项目2
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 项目2.o
LINKOBJ  = 项目2.o
LIBS     = -L"C:/Users/朱家贞/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/朱家贞/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/朱家贞/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/朱家贞/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/朱家贞/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/朱家贞/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/朱家贞/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/朱家贞/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/朱家贞/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = 项目2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

项目2.o: 项目2.c
	$(CC) -c 项目2.c -o 项目2.o $(CFLAGS)
